# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lfq < Formula
  desc ""
  homepage "https://github.com/danielcmessias/lfq"
  version "0.0.4"

  on_macos do
    url "https://github.com/danielcmessias/lfq/releases/download/v0.0.4/lfq_0.0.4_darwin_all.tar.gz"
    sha256 "6ad6ed6ecf80adc5e03a02e56f2b61754caaabb07c85164027b7c324cf77cd5a"

    def install
      bin.install "lfq"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danielcmessias/lfq/releases/download/v0.0.4/lfq_0.0.4_linux_amd64.tar.gz"
      sha256 "d779067a97e4035c66fbbe9698b8b54e05eea4063ba641076b24ab1ae1d9de05"

      def install
        bin.install "lfq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielcmessias/lfq/releases/download/v0.0.4/lfq_0.0.4_linux_arm64.tar.gz"
      sha256 "ba7f22cf75c7b8c91f3fce8cf656da34bcaf11aab59dc7c3d1a8e0daf58947dc"

      def install
        bin.install "lfq"
      end
    end
  end
end
