# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sawsy < Formula
  desc ""
  homepage "https://github.com/danielcmessias/sawsy"
  version "0.0.1"

  on_macos do
    url "https://github.com/danielcmessias/sawsy/releases/download/v0.0.1/sawsy_0.0.1_darwin_all.tar.gz"
    sha256 "ec7c4db4520a1e6d05127a794ad6be770f6ba76cfd585c58bd49113679335db4"

    def install
      bin.install "sawsy"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielcmessias/sawsy/releases/download/v0.0.1/sawsy_0.0.1_linux_arm64.tar.gz"
      sha256 "41c055261ade78cb3225221aa994a74c42c88c27f2740fa24aeae61cd8f4375d"

      def install
        bin.install "sawsy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/danielcmessias/sawsy/releases/download/v0.0.1/sawsy_0.0.1_linux_amd64.tar.gz"
      sha256 "81a13c6f1ca6a71b632231de8559098c27712e3a01540b77fce515d277eb8ecf"

      def install
        bin.install "sawsy"
      end
    end
  end
end
